# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'P2PClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  pod 'RxSwift'
  pod 'RxRelay'
  target 'P2PClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'P2PClientUITests' do
    # Pods for testing
  end

end
